name: Feature Test
on:
    push:
        branches:
            - feature/**
            - main
jobs:
    feature-test:
        name: "Feature Test"
        uses: muselab-d2x/d2x/.github/workflows/2gp-feature-test.yml@main
        secrets:
            dev-hub-auth-url: "${{ secrets.DEV_HUB_AUTH_URL }}"
            gh-email: "${{ secrets.gh_email }}"
